/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R04RouteImport } from './routes/04'
import { Route as R03RouteImport } from './routes/03'
import { Route as R02RouteImport } from './routes/02'
import { Route as R01RouteImport } from './routes/01'
import { Route as R00RouteImport } from './routes/00'
import { Route as IndexRouteImport } from './routes/index'

const R04Route = R04RouteImport.update({
  id: '/04',
  path: '/04',
  getParentRoute: () => rootRouteImport,
} as any)
const R03Route = R03RouteImport.update({
  id: '/03',
  path: '/03',
  getParentRoute: () => rootRouteImport,
} as any)
const R02Route = R02RouteImport.update({
  id: '/02',
  path: '/02',
  getParentRoute: () => rootRouteImport,
} as any)
const R01Route = R01RouteImport.update({
  id: '/01',
  path: '/01',
  getParentRoute: () => rootRouteImport,
} as any)
const R00Route = R00RouteImport.update({
  id: '/00',
  path: '/00',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/00': typeof R00Route
  '/01': typeof R01Route
  '/02': typeof R02Route
  '/03': typeof R03Route
  '/04': typeof R04Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/00': typeof R00Route
  '/01': typeof R01Route
  '/02': typeof R02Route
  '/03': typeof R03Route
  '/04': typeof R04Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/00': typeof R00Route
  '/01': typeof R01Route
  '/02': typeof R02Route
  '/03': typeof R03Route
  '/04': typeof R04Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/00' | '/01' | '/02' | '/03' | '/04'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/00' | '/01' | '/02' | '/03' | '/04'
  id: '__root__' | '/' | '/00' | '/01' | '/02' | '/03' | '/04'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R00Route: typeof R00Route
  R01Route: typeof R01Route
  R02Route: typeof R02Route
  R03Route: typeof R03Route
  R04Route: typeof R04Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/04': {
      id: '/04'
      path: '/04'
      fullPath: '/04'
      preLoaderRoute: typeof R04RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/03': {
      id: '/03'
      path: '/03'
      fullPath: '/03'
      preLoaderRoute: typeof R03RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/02': {
      id: '/02'
      path: '/02'
      fullPath: '/02'
      preLoaderRoute: typeof R02RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/01': {
      id: '/01'
      path: '/01'
      fullPath: '/01'
      preLoaderRoute: typeof R01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/00': {
      id: '/00'
      path: '/00'
      fullPath: '/00'
      preLoaderRoute: typeof R00RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R00Route: R00Route,
  R01Route: R01Route,
  R02Route: R02Route,
  R03Route: R03Route,
  R04Route: R04Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
